package control

// A2AServeStepDescriptors returns the StepDescriptor for the a2a_serve step.
// This step is auto-generated by Sync when an app has protocol.a2a configured —
// customers do not add it manually.
func A2AServeStepDescriptors() []StepDescriptor {
	return []StepDescriptor{
		{
			Type:        "a2a_serve",
			Title:       "Serve A2A",
			Category:    "ai",
			Capability:  "agent",
			Description: "Handle incoming A2A (Agent-to-Agent) JSON-RPC 2.0 requests. Routes tasks/send to configured skill flows via HTTP dispatch. Auto-generated by Studio when app.protocol.a2a is set — do not add manually.",
			Fields: []StepField{
				sf("input.skills_json", "Skill routes (JSON)", `{"skill_id":"/api/path"}`, ""),
				sf("input.gateway_base", "Gateway base URL", "http://localhost:8080", ""),
				sf("input.timeout_ms", "Timeout (ms)", "30000", "30000"),
			},
		},
	}
}
